#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$PLUGIN_AVAILABLE_PATH/traefik/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-traefik-list() {
  ls "${DOKKU_LIB_ROOT}/data/traefik/config/" | while read line; do
    declare APP="$(basename ${line} .yaml)";
    echo "${APP}";
  done
}

cmd-traefik-enable() {
  declare APP="$1"
  echo "Configuring ${APP}..."
  cat <<EOF > "${DOKKU_LIB_ROOT}/data/traefik/config/${APP}.yaml"
http:
  routers:
    ${APP}:
      rule: Host(`dokku.maayanlab.u8sand.net`)
      entryPoints:
        - websecure
      service: ${APP}
      tls:
        certResolver: letsencrypt
  services:
    ${APP}:
      loadBalancer:
        servers:
          - url: http://172.17.0.1:80/
EOF
}
cmd-traefik-disable() {
  declare APP="$1"
  echo "Disabling ${APP}..."
  rm "${DOKKU_LIB_ROOT}/data/traefik/config/${APP}.yaml"
}

cmd-traefik-configure() {
  if [ "${LETSENCRYPT_EMAIL}" == "" ]; then 
    echo "LETSENCRYPT_EMAIL is required";
    exit 1;
  fi

  mkdir -p "${DOKKU_LIB_ROOT}/data/traefik/config" "${DOKKU_LIB_ROOT}/data/traefik/data"
  cat <<EOF > "${DOKKU_LIB_ROOT}/data/traefik/traefik.yaml"
providers:
  file:
    directory: /config
    watch: true

entryPoints:
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${LETSENCRYPT_EMAIL}"
      storage: "/data/acme.json"
      tlsChallenge: {}
EOF
}

cmd-traefik-start() {
  if [ "$(docker ps -qf name=${PLUGIN_CONTAINER_NAME})" != ""]; then
    echo "Traefik is already running.";
    exit 0;
  fi

  cmd-traefik-configure

  docker run -d --rm \
    --name="${PLUGIN_CONTAINER_NAME}" \
    --network=host \
    --restart=unless-stopped \
    -v "${DOKKU_LIB_ROOT}/data/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
    -v "${DOKKU_LIB_ROOT}/data/traefik/config:/config"
    -v "${DOKKU_LIB_ROOT}/data/traefik/data:/data"
    traefik
}

cmd-traefik-stop() {
  docker stop "${PLUGIN_CONTAINER_NAME}"
}

cmd-traefik-restart() {
  cmd-traefik-stop()
  cmd-traefik-start()
}

cmd-traefik-logs() {
  docker logs -f "${PLUGIN_CONTAINER_NAME}"
}
