#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
if [[ -f "$PLUGIN_AVAILABLE_PATH/docker-options/functions" ]]; then
  source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"
fi

cmd-traefik-list() {
  ls "${PLUGIN_DATA_ROOT}/config/" | while read line; do
    declare APP="$(basename ${line} .yaml)";
    echo "${APP}";
  done
}

cmd-traefik-enable() {
  declare APP="$1"
  echo "Configuring ${APP}..."
  cat <<EOF > "${PLUGIN_DATA_ROOT}/config/${APP}.yaml"
http:
  routers:
    ${APP}:
      rule: Host(`dokku.maayanlab.u8sand.net`)
      entryPoints:
        - websecure
      service: ${APP}
      tls:
        certResolver: letsencrypt
  services:
    ${APP}:
      loadBalancer:
        servers:
          - url: http://172.17.0.1:80/
EOF
}
cmd-traefik-disable() {
  declare APP="$1"
  echo "Disabling ${APP}..."
  rm "${PLUGIN_DATA_ROOT}/config/${APP}.yaml"
}

cmd-traefik-configure() {
  if [ "${LETSENCRYPT_EMAIL}" == "" ]; then 
    echo "LETSENCRYPT_EMAIL is required";
    exit 1;
  fi

  mkdir -p "${PLUGIN_DATA_ROOT}/config" "${PLUGIN_DATA_ROOT}/data"
  cat <<EOF > "${PLUGIN_DATA_ROOT}/traefik.yaml"
providers:
  file:
    directory: /config
    watch: true

entryPoints:
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${LETSENCRYPT_EMAIL}"
      storage: "/data/acme.json"
      tlsChallenge: {}
EOF
}

cmd-traefik-start() {
  if [ "$(docker ps -qf name=${PLUGIN_CONTAINER_NAME})" != ""]; then
    echo "Traefik is already running.";
    exit 0;
  fi

  cmd-traefik-configure

  docker run -d --rm \
    --name="${PLUGIN_CONTAINER_NAME}" \
    --network=host \
    --restart=unless-stopped \
    -v "${PLUGIN_DATA_ROOT}/traefik.yaml:/etc/traefik/traefik.yaml"
    -v "${PLUGIN_DATA_ROOT}/config/:/config"
    -v "${PLUGIN_DATA_ROOT}/data/:/data"
    traefik
}

cmd-traefik-stop() {
  docker stop "${PLUGIN_CONTAINER_NAME}"
}

cmd-traefik-restart() {
  cmd-traefik-stop()
  cmd-traefik-start()
}

cmd-traefik-logs() {
  docker logs -f "${PLUGIN_CONTAINER_NAME}"
}
