#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-traefik-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="traefik"
  local plugin_description="Manage the traefik integration"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    traefik:enable <app>, Enable or renew traefik for an app
    traefik:disable <app>, Disable traefik for an app
    traefik:list, List traefik-served apps
    traefik:start, Start traefik service
    traefik:restart, Restart traefik service
    traefik:stop, Stop traefik service
    traefik:logs, Show traefik logs
    traefik:help, Display traefik help
help_content
}
